
# ci/pipeline.yml
#
# DO NOT MAKE CHANGES TO THIS FILE. Instead, modify ci/pipeline.yml.erb and
# execute build-pipeline-yml.
#
# created: 2020-09-08T14:16:24+09:00
#
resource_types:
- name: file-url
  type: docker-image
  source:
    repository: pivotalservices/concourse-curl-resource
    tag: latest

resources:
- name: ubuntu-18.04
  type: docker-image
  source:
    repository: ubuntu
    tag: "18.04"

- name: kubernetes-resource
  type: git
  source:
    uri: https://github.com/cappyzawa/kubernetes-resource.git
    branch: master

- name: kubernetes-resource-release
  type: git
  source:
    uri: https://github.com/cappyzawa/kubernetes-resource.git
    branch: master
    tag_filter: v*


- name: kubernetes-resource-image-1.15
  type: docker-image
  source:
    repository: ghcr.io/cappyzawa/kubernetes-resource
    tag: "1.15"
    username: ((docker-username))
    password: ((docker-password))

- name: kubernetes-resource-image-1.16
  type: docker-image
  source:
    repository: ghcr.io/cappyzawa/kubernetes-resource
    tag: "1.16"
    username: ((docker-username))
    password: ((docker-password))

- name: kubernetes-resource-image-1.17
  type: docker-image
  source:
    repository: ghcr.io/cappyzawa/kubernetes-resource
    tag: "1.17"
    username: ((docker-username))
    password: ((docker-password))

- name: kubernetes-resource-image-1.18
  type: docker-image
  source:
    repository: ghcr.io/cappyzawa/kubernetes-resource
    tag: "1.18"
    username: ((docker-username))
    password: ((docker-password))

- name: kubernetes-resource-image-1.19
  type: docker-image
  source:
    repository: ghcr.io/cappyzawa/kubernetes-resource
    tag: "1.19"
    username: ((docker-username))
    password: ((docker-password))

- name: kubernetes-resource-image-latest
  type: docker-image
  source:
    repository: ghcr.io/cappyzawa/kubernetes-resource
    tag: "latest"
    username: ((docker-username))
    password: ((docker-password))


- name: kubernetes-resource-image-edge
  type: docker-image
  source:
    repository: ghcr.io/cappyzawa/kubernetes-resource
    tag: edge
    username: ((docker-username))
    password: ((docker-password))


- name: stable-1.15
  type: file-url
  source:
    url: https://storage.googleapis.com/kubernetes-release/release/stable-1.15.txt
    filename: version

- name: stable-1.16
  type: file-url
  source:
    url: https://storage.googleapis.com/kubernetes-release/release/stable-1.16.txt
    filename: version

- name: stable-1.17
  type: file-url
  source:
    url: https://storage.googleapis.com/kubernetes-release/release/stable-1.17.txt
    filename: version

- name: stable-1.18
  type: file-url
  source:
    url: https://storage.googleapis.com/kubernetes-release/release/stable-1.18.txt
    filename: version

- name: stable-1.19
  type: file-url
  source:
    url: https://storage.googleapis.com/kubernetes-release/release/stable-1.19.txt
    filename: version

- name: latest
  type: file-url
  source:
    url: https://storage.googleapis.com/kubernetes-release/release/latest.txt
    filename: version


jobs:
- name: build-kubernetes-resource-image-edge
  public: true
  serial: true
  plan:
  - do:
    - aggregate:
      - get: kubernetes-resource
        trigger: true
      - get: ubuntu-18.04
        params: {save: true}
        trigger: true
      - get: latest
        trigger: true
    - task: build-build-args-file
      file: kubernetes-resource/ci/tasks/build-build-args-file.yml
      input_mapping: {version: latest}
    - put: kubernetes-resource-image-edge
      params:
        build: kubernetes-resource
        load_base: ubuntu-18.04
        build_args_file: output/build-args-file


- name: build-kubernetes-resource-image-1.15
  public: true
  serial: true
  plan:
  - do:
    - aggregate:
      - get: kubernetes-resource-release
        trigger: true
      - get: ubuntu-18.04
        params: {save: true}
        trigger: true
      - get: stable-1.15
        trigger: true
    - task: build-build-args-file
      file: kubernetes-resource-release/ci/tasks/build-build-args-file.yml
      input_mapping: {version: stable-1.15}
    - put: kubernetes-resource-image-1.15
      params:
        build: kubernetes-resource-release
        load_base: ubuntu-18.04
        build_args_file: output/build-args-file

- name: build-kubernetes-resource-image-1.16
  public: true
  serial: true
  plan:
  - do:
    - aggregate:
      - get: kubernetes-resource-release
        trigger: true
      - get: ubuntu-18.04
        params: {save: true}
        trigger: true
      - get: stable-1.16
        trigger: true
    - task: build-build-args-file
      file: kubernetes-resource-release/ci/tasks/build-build-args-file.yml
      input_mapping: {version: stable-1.16}
    - put: kubernetes-resource-image-1.16
      params:
        build: kubernetes-resource-release
        load_base: ubuntu-18.04
        build_args_file: output/build-args-file

- name: build-kubernetes-resource-image-1.17
  public: true
  serial: true
  plan:
  - do:
    - aggregate:
      - get: kubernetes-resource-release
        trigger: true
      - get: ubuntu-18.04
        params: {save: true}
        trigger: true
      - get: stable-1.17
        trigger: true
    - task: build-build-args-file
      file: kubernetes-resource-release/ci/tasks/build-build-args-file.yml
      input_mapping: {version: stable-1.17}
    - put: kubernetes-resource-image-1.17
      params:
        build: kubernetes-resource-release
        load_base: ubuntu-18.04
        build_args_file: output/build-args-file

- name: build-kubernetes-resource-image-1.18
  public: true
  serial: true
  plan:
  - do:
    - aggregate:
      - get: kubernetes-resource-release
        trigger: true
      - get: ubuntu-18.04
        params: {save: true}
        trigger: true
      - get: stable-1.18
        trigger: true
    - task: build-build-args-file
      file: kubernetes-resource-release/ci/tasks/build-build-args-file.yml
      input_mapping: {version: stable-1.18}
    - put: kubernetes-resource-image-1.18
      params:
        build: kubernetes-resource-release
        load_base: ubuntu-18.04
        build_args_file: output/build-args-file

- name: build-kubernetes-resource-image-1.19
  public: true
  serial: true
  plan:
  - do:
    - aggregate:
      - get: kubernetes-resource-release
        trigger: true
      - get: ubuntu-18.04
        params: {save: true}
        trigger: true
      - get: stable-1.19
        trigger: true
    - task: build-build-args-file
      file: kubernetes-resource-release/ci/tasks/build-build-args-file.yml
      input_mapping: {version: stable-1.19}
    - put: kubernetes-resource-image-1.19
      params:
        build: kubernetes-resource-release
        load_base: ubuntu-18.04
        build_args_file: output/build-args-file

- name: build-kubernetes-resource-image-latest
  public: true
  serial: true
  plan:
  - do:
    - aggregate:
      - get: kubernetes-resource-release
        trigger: true
      - get: ubuntu-18.04
        params: {save: true}
        trigger: true
      - get: latest
        trigger: true
    - task: build-build-args-file
      file: kubernetes-resource-release/ci/tasks/build-build-args-file.yml
      input_mapping: {version: latest}
    - put: kubernetes-resource-image-latest
      params:
        build: kubernetes-resource-release
        load_base: ubuntu-18.04
        build_args_file: output/build-args-file

